"""
Django settings for ecampus_api project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import datetime
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent.parent

#Auth Model
AUTH_USER_MODEL = "user.AuthUser"

#URLS

ROOT_URLCONF = 'ecampus_api.urls'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'django_cleanup',
    'user',
    'drf_yasg',
    'rest_framework_api_key',
    'api_authentication',
    'roles_and_permission',
    'employee',
    'modules',
    'master',
    'preadmission',
    'student',
    'fee',
    'attendance',
    'sendsms',
    'dbbackup',
    'base',
    'phone_field',
    'exam_management',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api_authentication.authentication.APITokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'api_authentication.permissions.HasOrganizationAPIKey',
        'rest_framework.permissions.IsAuthenticated',
        'employee.permissions.EmployeeHasSpecificPermission',
    ],
    'DEFAULT_RENDERER_CLASSES':[
        'base.renderers.APIJSONRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'base.pagination.APIPagination',
    'PAGE_SIZE': 30,
    'EXCEPTION_HANDLER': 'base.handlers.ecampus_exception_handler'
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(days=7 ),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=7),
    'AUTH_HEADER_TYPES': 'eCampus',
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
}

API_KEY_CUSTOM_HEADER = "HTTP_X_API_KEY"

WSGI_APPLICATION = 'ecampus_api.wsgi.application'

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-api-key',
    'Content-Type',
    'Content-Disposition',
    'Access-Control-Allow-Origin',
    'featureperm',
]

PERMISSION_APP_NAMES = [
    'auth',
    'employee',
    ]

PERMISSION_MODEL_NAMES = [
    'group',
    'employee',
    ]

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

APPLICATION_DOMAIN = 'http://creaxiotechnologies.com'
SCHOOL_NAME = 'creaxio school - Creaxio'
SUCCESS_CODES = (200, 201, 202, 204, 206, )

GENDER_CHOICES = (('male','Male'), ('female','Female'), ('other','Other'))

COMBINATION_CHOICES = (('state','State'), ('cbse','CBSE'), ('icse','ICSE'))

QUOTA_CHOICES = (('rte','RTE'), ('management','management'))

PRIMARY_CONTACT_CHOICE = (('father','Father'),('mother','Mother'),('guardian','Guardian'))

EXISTING_PARENT_CHOICES = (('yes','Yes'), ('no','No'))

FEE_TYPE_CHOICES = (('monthly', 'Monthly'), ('annual', 'Annual'))
